/*
* Rekor
*
* Rekor is a cryptographically secure, immutable transparency log for signed software releases.
*
* The version of the OpenAPI document: 0.0.1
*
* Generated by: https://openapi-generator.tech
*/

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct Dsse {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "apiVersion")]
    pub api_version: String,
    #[serde(rename = "spec")]
    pub spec: Spec,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct Spec {
    #[serde(rename = "root", skip_serializing_if = "Option::is_none")]
    pub root: Option<String>,
    #[serde(rename = "proposedContent")]
    pub proposed_content: ProposedContent,
    #[serde(rename = "payloadHash", skip_serializing_if = "Option::is_none")]
    pub payload_hash: Option<Hash>,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct ProposedContent {
    #[serde(rename = "envelope", skip_serializing_if = "Option::is_none")]
    pub envelope: Option<String>,
    #[serde(rename = "verifiers")]
    pub verifiers: Vec<String>,
}

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
pub struct Hash {
    #[serde(rename = "algorithm")]
    pub algorithm: String,
    #[serde(rename = "value")]
    pub value: String,
}
