/*
* Rekor
*
* Rekor is a cryptographically secure, immutable transparency log for signed software releases.
*
* The version of the OpenAPI document: 0.0.1
*
* Generated by: https://openapi-generator.tech
*/
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Eq, PartialEq, Serialize, Deserialize)]
#[serde(tag = "kind")]
pub enum ProposedEntry {
    #[serde(rename = "alpine")]
    Alpine {
        #[serde(rename = "apiVersion")]
        api_version: String,
        #[serde(rename = "spec")]
        spec: serde_json::Value,
    },
    #[serde(rename = "hashedrekord")]
    Hashedrekord {
        #[serde(rename = "apiVersion")]
        api_version: String,
        #[serde(rename = "spec")]
        spec: super::hashedrekord::Spec,
    },
    #[serde(rename = "helm")]
    Helm {
        #[serde(rename = "apiVersion")]
        api_version: String,
        #[serde(rename = "spec")]
        spec: serde_json::Value,
    },
    #[serde(rename = "intoto")]
    Intoto {
        #[serde(rename = "apiVersion")]
        api_version: String,
        #[serde(rename = "spec")]
        spec: serde_json::Value,
    },
    #[serde(rename = "jar")]
    Jar {
        #[serde(rename = "apiVersion")]
        api_version: String,
        #[serde(rename = "spec")]
        spec: serde_json::Value,
    },
    #[serde(rename = "rekord")]
    Rekord {
        #[serde(rename = "apiVersion")]
        api_version: String,
        #[serde(rename = "spec")]
        spec: serde_json::Value,
    },
    #[serde(rename = "rfc3161")]
    Rfc3161 {
        #[serde(rename = "apiVersion")]
        api_version: String,
        #[serde(rename = "spec")]
        spec: serde_json::Value,
    },
    #[serde(rename = "rpm")]
    Rpm {
        #[serde(rename = "apiVersion")]
        api_version: String,
        #[serde(rename = "spec")]
        spec: serde_json::Value,
    },
    #[serde(rename = "tuf")]
    Tuf {
        #[serde(rename = "apiVersion")]
        api_version: String,
        #[serde(rename = "spec")]
        spec: serde_json::Value,
    },
}
