/*
 * Rekor
 *
 * Rekor is a cryptographically secure, immutable transparency log for signed software releases.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Default, Serialize, Deserialize)]
pub struct RekorVersion {
    #[serde(rename = "version")]
    pub version: String,
    #[serde(rename = "commit")]
    pub commit: String,
    #[serde(rename = "treestate")]
    pub treestate: String,
    #[serde(rename = "builddate")]
    pub builddate: String,
}

impl RekorVersion {
    pub fn new(
        version: String,
        commit: String,
        treestate: String,
        builddate: String,
    ) -> RekorVersion {
        RekorVersion {
            version,
            commit,
            treestate,
            builddate,
        }
    }
}
