/*
 * Rekor
 *
 * Rekor is a cryptographically secure, immutable transparency log for signed software releases.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

/// Rfc3161 : RFC3161 Timestamp
use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, PartialEq, Eq, Default, Serialize, Deserialize)]
pub struct Rfc3161 {
    #[serde(rename = "kind")]
    pub kind: String,
    #[serde(rename = "apiVersion")]
    pub api_version: String,
    #[serde(rename = "spec")]
    pub spec: serde_json::Value,
}

impl Rfc3161 {
    /// RFC3161 Timestamp
    pub fn new(kind: String, api_version: String, spec: serde_json::Value) -> Rfc3161 {
        Rfc3161 {
            kind,
            api_version,
            spec,
        }
    }
}
