/*
 * Rekor
 *
 * Rekor is a cryptographically secure, immutable transparency log for signed software releases.
 *
 * The version of the OpenAPI document: 0.0.1
 *
 * Generated by: https://openapi-generator.tech
 */

use serde::{Deserialize, Serialize};

#[derive(Clone, Debug, Eq, PartialEq, Default, Serialize, Deserialize)]
pub struct SearchLogQuery {
    #[serde(rename = "entryUUIDs", skip_serializing_if = "Option::is_none")]
    pub entry_uuids: Option<Vec<String>>,
    #[serde(rename = "logIndexes", skip_serializing_if = "Option::is_none")]
    pub log_indexes: Option<Vec<i32>>,
    #[serde(rename = "entries", skip_serializing_if = "Option::is_none")]
    pub entries: Option<Vec<crate::rekor::models::ProposedEntry>>,
}

impl SearchLogQuery {
    pub fn new() -> SearchLogQuery {
        SearchLogQuery {
            entry_uuids: None,
            log_indexes: None,
            entries: None,
        }
    }
}
