name: Publish-Crate-Upon-Release
on:
  release:
    types: [published]

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  publish-automatically:
    name: Publish crates
    runs-on: ubuntu-latest
    permissions:
      id-token: write # needed to get OpenID Connect token for authentication

    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v7.0.0
        with:
          persist-credentials: false

      - uses: rust-lang/crates-io-auth-action@bbd81622f20ce9e2dd9622e3218b975523e45bbe # v1.0.4
        id: auth

      - name: Rustup
        run: |
          rustup install stable
          rustup override set stable

      - name: publish crates
        env:
          CARGO_REGISTRY_TOKEN: "${{ steps.auth.outputs.token }}"
        run: cargo publish
