on: [workflow_dispatch]

name: Conformance Suite

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
  cancel-in-progress: true

jobs:
  conformance:
    name: Check sigstore conformance
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@df4cb1c069e1874edd31b4311f1884172cec0e10 # v6.0.3
        with:
          persist-credentials: false
      - name: Rustup
        run: |
          rustup install --profile minimal stable
          rustup override set stable
      - uses: Swatinem/rust-cache@c19371144df3bb44fab255c43d04cbc2ab54d1c4 # v2.9.1
      - run: |
          cargo build --manifest-path=tests/conformance/Cargo.toml
      - uses: sigstore/sigstore-conformance@main
        with:
          entrypoint: ${{ github.workspace }}/tests/conformance/target/debug/sigstore
